package server

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/toustifer/agentflow/pkg/engine"
)

// agentflowGitRulesTemplate is the canonical agentflow-git.md content.
const agentflowGitRulesTemplate = `# agentflow-git.md

> Auto-generated by agentflow.project_init. Workers must follow these rules on every dispatch.
> Do not edit by hand; run project_init again to regenerate.

## Workspace rule

Workers only modify files inside their assigned worktree_path. Direct changes
under the repo root are forbidden. Use worktree_get to confirm the path
before editing.

## Branch binding

Each DAG owns exactly one feature branch. Before committing, verify
task.metadata.git.branch matches the DAG via task_get. If empty or mismatched,
stop and call task_get again.

## Standard task flow

` + "```" + `
cd $worktree_path
git status
git log -n 1
<edit>
<test>
git add -p
git commit -m "task=<task_id>: <summary>"
` + "```" + `

## Forbidden actions

- force push (git push --force / -f)
- push to main
- cherry-pick across DAGs
- edits in another worker's tree
- skipping worker_diary_write
- merging without a review_pending pass

## Review handoff contract

Before task_transition submit, the worker must produce:
- clean git status
- commit hash stored under task.metadata.review.commit
- diff text stored under task.metadata.review.diff
- updated project docs (doc_write) when modules changed
- a worker_diary_write entry for today's date
- a one-line test summary if tests changed

The MCP server captures HEAD and diff automatically on submit; workers must
not skip the diary step.

## Failure handling

On conflict: git fetch && git rebase && git status. Never rebase a published
commit without permission. If a worktree is broken, stop and report via
worktree_get instead of self-repairing.
`

func writeRulesFile(claudeDir string) (string, error) {
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return "", fmt.Errorf("create .claude dir: %w", err)
	}
	target := filepath.Join(claudeDir, "agentflow-git.md")
	if err := os.WriteFile(target, []byte(agentflowGitRulesTemplate), 0o644); err != nil {
		return "", fmt.Errorf("write rules file: %w", err)
	}
	return agentflowGitRulesTemplate, nil
}

type projectInitResult struct {
	namespace *engine.Namespace
	payload   map[string]any
}

func (s *Server) handleProjectInit(ctx context.Context, input map[string]any) (projectInitResult, error) {
	projectID, err := requiredString(input, "project_id")
	if err != nil {
		return projectInitResult{}, err
	}
	workdir, err := requiredString(input, "workdir")
	if err != nil {
		return projectInitResult{}, err
	}
	projectName, _ := optionalString(input, "project_name")
	if projectName == "" {
		projectName = projectID
	}
	initGit := true
	if raw, ok := input["init_git"]; ok {
		if v, ok := raw.(bool); ok {
			initGit = v
		}
	}
	mainBranch, _ := optionalString(input, "main_branch")
	if mainBranch == "" {
		mainBranch = "main"
	}
	worktreeRoot, _ := optionalString(input, "worktree_root")
	userName, _ := optionalString(input, "user_name")
	userEmail, _ := optionalString(input, "user_email")

	if conflict, owner := s.workdirConflict(ctx, workdir); conflict {
		return projectInitResult{}, fmt.Errorf(
			"workdir %q 已被 namespace %q 占用，无法重复 project_init", workdir, owner)
	}

	repoPath, branch, err := ensureReadyGitRepo(ctx, workdir, mainBranch, initGit, userName, userEmail)
	if err != nil {
		return projectInitResult{}, err
	}
	hasHeadCommit, err := repoHasHeadCommit(ctx, repoPath)
	if err != nil {
		return projectInitResult{}, err
	}

	resolvedWorktreeRoot := worktreeRoot
	if resolvedWorktreeRoot == "" {
		parent := filepath.Dir(repoPath)
		resolvedWorktreeRoot = filepath.Join(parent, ".agentflow-worktrees", filepath.Base(repoPath))
	}

	ns, err := s.engine.CreateNamespace(ctx, engine.CreateNamespaceRequest{
		ID:   projectID,
		Name: projectName,
		Metadata: map[string]string{
			"workdir":          repoPath,
			"git_main_branch":  branch,
			"worktree_root":    resolvedWorktreeRoot,
			"git.initialized":  gitInitializedMarker(initGit),
			"git.has_head":     boolString(hasHeadCommit),
		},
	})
	if err != nil {
		return projectInitResult{}, err
	}

	claudeDir := filepath.Join(repoPath, ".claude")
	if _, err := writeRulesFile(claudeDir); err != nil {
		_ = s.engine.DeleteNamespace(ctx, projectID, true)
		return projectInitResult{}, err
	}

	return projectInitResult{
		namespace: ns,
		payload: map[string]any{
			"namespace_id":    ns.ID,
			"project_name":    ns.Name,
			"repo_path":       repoPath,
			"main_branch":     branch,
			"worktree_root":   resolvedWorktreeRoot,
			"rules_file_path": filepath.Join(claudeDir, "agentflow-git.md"),
			"git_initialized": initGit,
			"has_head_commit": hasHeadCommit,
		},
	}, nil
}

func boolString(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

func gitInitializedMarker(initGit bool) string {
	if initGit {
		return "true"
	}
	return "already_a_repo"
}

func (s *Server) workdirConflict(ctx context.Context, workdir string) (bool, string) {
	all, err := s.engine.ListNamespaces(ctx)
	if err != nil {
		return false, ""
	}
	for _, ns := range all {
		if ns.Metadata == nil {
			continue
		}
		if w, ok := ns.Metadata["workdir"]; ok && strings.EqualFold(w, workdir) {
			return true, ns.ID
		}
	}
	return false, ""
}
